const VACCINATION_STATE = {
    REGISTERED: 'REGISTERED',
    BOOKED: 'BOOKED',
    RECEIVED_FIRST: 'RECEIVED_FIRST',
    RECEIVED_SECOND: 'RECEIVED_SECOND',
    VACCINATED: 'VACCINATED'
}

module.exports = {VACCINATION_STATE};